module.exports.sectors = ['communication services', 'consumer discretionary', 'consumer staples', 'energy', 'financials', 'health care', 'industrials', 'information technology', 'materials', 'real estate', 'utilities'];

module.exports.industryGroups = ['energy', 'materials', 'capital goods', 'commercial and professional services', 'transportation', 'automobiles and components', 'consumer durables and apparel', 'consumer services', 'retailing', 'food and staples retailing', 'food, beverage and tobacco', 'household and personal products', 'health care equipment and services', 'pharmaceuticals, biotechnology and life sciences', 'banks', 'diversified financials', 'insurance', 'software and services', 'technology hardware and equipment', 'semiconductors and semiconductor equipment', 'communication services', 'media and entertainment', 'utilities', 'real estate'];

module.exports.industries = ['energy equipment and services', 'oil, gas and consumable fuels', 'chemicals', 'construction materials', 'containers and packaging', 'metals and mining', 'paper and forest products', 'aerospace and defense', 'building products', 'construction and engineering', 'electrical equipment', 'industrial conglomerates', 'machinery', 'trading companies and distributors', 'commercial services and supplies', 'professional services', 'air freight and logistics', 'airlines', 'marine', 'road and rail', 'transportation infrastructure', 'auto components', 'automobiles', 'household durables', 'leisure products', 'textiles, apparel and luxury goods', 'hotels, restaurants and leisure', 'diversified consumer services', 'distributors', 'internet and direct marketing retail', 'multiline retail', 'specialty retail', 'food and staples retailing', 'beverages', 'food products', 'tobacco', 'household products', 'personal products', 'health care equipment and supplies', 'health care providers and services', 'health care technology', 'biotechnology', 'pharmaceuticals', 'life sciences tools and services', 'banks', 'thrifts and mortgage finance', 'diversified financial services', 'consumer finance', 'capital markets', 'mortgage real estate investment trusts', 'insurance', 'it services', 'software', 'communications equipment', 'technology hardware, storage and peripherals', 'electronic equipment, instruments and components', 'semiconductors and semiconductor equipment', 'diversified telecommunication services', 'wireless telecommunication services', 'media', 'entertainment', 'interactive media and services', 'electric utilities', 'gas utilities', 'multi-utilities', 'water utilities', 'independent power and renewable electricity producers', 'equity real estate investment trusts', 'real estate management and development'];

module.exports.subindustries = ['oil and gas drilling'
    , 'oil and gas equipment and services'
    , 'integrated oil and gas'
    , 'oil and gas exploration and production'
    , 'oil and gas refining and marketing'
    , 'oil and gas storage and transportation'
    , 'coal and consumable fuels'
    , 'commodity chemicals'
    , 'diversified chemicals'
    , 'fertilizers and agricultural chemicals'
    , 'industrial gases'
    , 'specialty chemicals'
    , 'construction materials'
    , 'metal and glass containers'
    , 'paper packaging'
    , 'aluminum'
    , 'diversified metals and mining'
    , 'copper'
    , 'gold'
    , 'precious metals and minerals'
    , 'silver'
    , 'steel'
    , 'forest products'
    , 'paper products'
    , 'aerospace and defense'
    , 'building products'
    , 'construction and engineering'
    , 'electrical components and equipment'
    , 'heavy electrical equipment'
    , 'industrial conglomerates'
    , 'construction machinery and heavy trucks'
    , 'agricultural and farm machinery'
    , 'industrial machinery'
    , 'trading companies and distributors'
    , 'commercial printing'
    , 'environmental and facilities services'
    , 'office services and supplies'
    , 'diversified support services'
    , 'security and alarm services'
    , 'human resource and employment services'
    , 'research and consulting services'
    , 'air freight and logistics'
    , 'airlines'
    , 'marine'
    , 'railroads'
    , 'trucking'
    , 'airport services'
    , 'highways and railtracks'
    , 'marine ports and services'
    , 'auto parts and equipment'
    , 'tires and rubber'
    , 'automobile manufacturers'
    , 'motorcycle manufacturers'
    , 'consumer electronics'
    , 'home furnishings'
    , 'homebuilding'
    , 'household appliances'
    , 'housewares and specialties'
    , 'leisure products'
    , 'apparel, accessories and luxury goods'
    , 'footwear'
    , 'textiles'
    , 'casinos and gaming'
    , 'hotels, resorts and cruise lines'
    , 'leisure facilities'
    , 'restaurants'
    , 'education services'
    , 'specialized consumer services'
    , 'distributors'
    , 'internet and direct marketing retail'
    , 'department stores'
    , 'general merchandise stores'
    , 'apparel retail'
    , 'computer and electronics retail'
    , 'home improvement retail'
    , 'specialty stores'
    , 'automotive retail'
    , 'homefurnishing retail'
    , 'drug retail'
    , 'food distributors'
    , 'food retail'
    , 'hypermarkets and super centers'
    , 'brewers'
    , 'distillers and vintners'
    , 'soft drinks'
    , 'agricultural products'
    , 'packaged foods and meats'
    , 'tobacco'
    , 'household products'
    , 'personal products'
    , 'health care equipment'
    , 'health care supplies'
    , 'health care distributors'
    , 'health care services'
    , 'health care facilities'
    , 'managed health care'
    , 'health care technology'
    , 'biotechnology'
    , 'pharmaceuticals'
    , 'life sciences tools and services'
    , 'diversified banks'
    , 'regional banks'
    , 'thrifts and mortgage finance'
    , 'other diversified financial services'
    , 'multi - sector holdings'
    , 'specialized finance'
    , 'consumer finance'
    , 'asset management and custody banks'
    , 'investment banking and brokerage'
    , 'diversified capital markets'
    , 'financial exchanges and data'
    , 'mortgage reits'
    , 'insurance brokers'
    , 'life and health insurance'
    , 'multi - line insurance'
    , 'property and casualty insurance'
    , 'reinsurance'
    , 'it consulting and other services'
    , 'data processing and outsourced services'
    , 'internet services and infrastructure'
    , 'application software'
    , 'systems software'
    , 'communications equipment'
    , 'technology hardware, storage and peripherals'
    , 'electronic equipment and instruments'
    , 'electronic components'
    , 'electronic manufacturing services'
    , 'technology distributors'
    , 'semiconductor equipment'
    , 'semiconductors'
    , 'alternative carriers'
    , 'integrated telecommunication services'
    , 'wireless telecommunication services'
    , 'advertising'
    , 'broadcasting'
    , 'cable and satellite'
    , 'publishing'
    , 'movies and entertainment'
    , 'interactive home entertainment'
    , 'interactive media and services'
    , 'electric utilities'
    , 'gas utilities'
    , 'multi - utilities'
    , 'water utilities'
    , 'independent power producers and energy traders'
    , 'renewable electricity'
    , 'diversified reits'
    , 'industrial reits'
    , 'hotel and resort reits'
    , 'office reits'
    , 'health care reits'
    , 'residential reits'
    , 'retail reits'
    , 'specialized reits'
    , 'diversified real estate activities'
    , 'real estate operating companies'
    , 'real estate development'
    , 'real estate services'];